---
  root: true
  parserOptions:
    ecmaVersion: 2015
    sourceType: "module"
  extends: "eslint:recommended"
  env:
    node: true
    es6: true
  rules:
    curly: 2
    dot-notation: 2
    func-style:
      - 2
      - "declaration"
      -
        allowArrowFunctions: true
    indent:
      - 2
      - 2
    key-spacing:
      - 2
      -
        beforeColon: false
        afterColon: true
    linebreak-style:
      - 2
      - "unix"
    max-len:
      - 2
      - 80
      - 4
    max-statements:
      - 1
      - 20
    no-implicit-globals: 2
    no-multi-spaces: 2
    no-new-wrappers: 2
    no-trailing-spaces: 2
    no-unused-expressions:
      - 2
      -
        allowShortCircuit: true
        allowTernary: true
    no-var: 2
    no-whitespace-before-property: 2
    one-var-declaration-per-line: 2
    quotes:
      - 2
      - "single"
    semi: 2
